// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAddUrlsParams creates a new AddUrlsParams object
// with the default values initialized.
func NewAddUrlsParams() AddUrlsParams {
	var ()
	return AddUrlsParams{}
}

// AddUrlsParams contains all the bound params for the add urls operation
// typically these are obtained from a http.Request
//
// swagger:parameters addURLs
type AddUrlsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Feed name
	  Required: true
	  In: query
	*/
	Name string
	/*Video URL list
	  Required: true
	  In: body
	*/
	Urls []string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *AddUrlsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qName, qhkName, _ := qs.GetOK("name")
	if err := o.bindName(qName, qhkName, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body []string
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("urls", "body"))
			} else {
				res = append(res, errors.NewParseError("urls", "body", "", err))
			}

		} else {

			if len(res) == 0 {
				o.Urls = body
			}
		}

	} else {
		res = append(res, errors.Required("urls", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AddUrlsParams) bindName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("name", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("name", "query", raw); err != nil {
		return err
	}

	o.Name = raw

	return nil
}
