// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetfeedsHandlerFunc turns a function with the right signature into a getfeeds handler
type GetfeedsHandlerFunc func(GetfeedsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetfeedsHandlerFunc) Handle(params GetfeedsParams) middleware.Responder {
	return fn(params)
}

// GetfeedsHandler interface for that can handle valid getfeeds params
type GetfeedsHandler interface {
	Handle(GetfeedsParams) middleware.Responder
}

// NewGetfeeds creates a new http.Handler for the getfeeds operation
func NewGetfeeds(ctx *middleware.Context, handler GetfeedsHandler) *Getfeeds {
	return &Getfeeds{Context: ctx, Handler: handler}
}

/*Getfeeds swagger:route GET /feeds getfeeds

Get a list of src video or gif

Get a list of src video or gif


*/
type Getfeeds struct {
	Context *middleware.Context
	Handler GetfeedsHandler
}

func (o *Getfeeds) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetfeedsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
