// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Magicking/secure-sunrise/models"
)

// GetfeedsOKCode is the HTTP code returned for type GetfeedsOK
const GetfeedsOKCode int = 200

/*GetfeedsOK List of URL source to be played


swagger:response getfeedsOK
*/
type GetfeedsOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewGetfeedsOK creates GetfeedsOK with default headers values
func NewGetfeedsOK() *GetfeedsOK {
	return &GetfeedsOK{}
}

// WithPayload adds the payload to the getfeeds o k response
func (o *GetfeedsOK) WithPayload(payload []string) *GetfeedsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the getfeeds o k response
func (o *GetfeedsOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetfeedsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetfeedsDefault Internal error

swagger:response getfeedsDefault
*/
type GetfeedsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetfeedsDefault creates GetfeedsDefault with default headers values
func NewGetfeedsDefault(code int) *GetfeedsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetfeedsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the getfeeds default response
func (o *GetfeedsDefault) WithStatusCode(code int) *GetfeedsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the getfeeds default response
func (o *GetfeedsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the getfeeds default response
func (o *GetfeedsDefault) WithPayload(payload *models.Error) *GetfeedsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the getfeeds default response
func (o *GetfeedsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetfeedsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
