// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "TODO",
    "title": "Secure sunriset",
    "version": "0.1.0"
  },
  "paths": {
    "/control/add": {
      "post": {
        "description": "Add a video URL to feed\n",
        "summary": "addURLs",
        "operationId": "addURLs",
        "parameters": [
          {
            "type": "string",
            "description": "Feed name",
            "name": "name",
            "in": "query",
            "required": true
          },
          {
            "description": "Video URL list",
            "name": "urls",
            "in": "body",
            "required": true,
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        ],
        "responses": {
          "200": {},
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/feeds": {
      "get": {
        "description": "Get a list of src video or gif\n",
        "produces": [
          "application/json"
        ],
        "summary": "Get a list of src video or gif",
        "operationId": "getfeeds",
        "parameters": [
          {
            "type": "string",
            "description": "Feed name",
            "name": "name",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "List of URL source to be played\n",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
}
